# Generated by Django 4.2.2 on 2024-05-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_board_url_job_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
