# Generated by Django 4.2.2 on 2024-05-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='career_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='degree',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
